- name: "Print message"
  ansible.builtin.debug:
    msg: "Test Config Apache"

- name: "Install module"
  ansible.builtin.lineinfile:
    path: "{{ apache_conf_httpd_conf }}"
    state: present
    line: 'LoadModule auth_digest_module modules/mod_auth_digest.so'
    insertafter: '^## MyModule'
    backup: true

- name: "Install module"
  ansible.builtin.lineinfile:
    path: "{{ apache_conf_app_conf }}"
    state: present
    regexp: '^(.*)#.*(RewriteEngine .*)'
    backrefs: true
    line: '\1\2'
    insertafter: '#  code here'
    backup: true

