- name: My first play
  hosts: all
  tasks:
   - name: "[{{ project_name }}] Ping my hosts"
     ansible.builtin.ping:

   - name: "[{{ project_name }}] Print message"
     ansible.builtin.debug:
      msg: Hello world
  roles:
    - role: role1
